openapi: 3.0.3
info:
  title: API di Autenticazione
  description: API per la gestione dell'autenticazione JWT
  version: 1.0.0
servers:
  - url: https://api.example.com/v1
    description: Server di produzione
  - url: https://staging.api.example.com/v1
    description: Server di staging
paths:
  /login:
    post:
      summary: Effettua il login
      description: Effettua il login e restituisce un token JWT
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - username
                - password
              properties:
                username:
                  type: string
                  example: 'utente@example.com'
                password:
                  type: string
                  example: 'passwordSicura'
      responses:
        '200':
          description: Login effettuato con successo
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    example: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c'
        '401':
          description: Credenziali non valide
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: 'Nome utente o password errati'
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          example: 1
        username:
          type: string
          example: 'utente@example.com'
        password:
          type: string
          example: 'passwordSicura'
security:
  - BearerAuth: []